---
- name: Create a container
  docker_container:
    name: casestudy-spring
    image: "{{ docker_image }}"
    ports:
    - "8080:8090"
  when:
    - ansible_connection != "docker"

- debug: msg="http://{{ inventory_hostname }}:8080 is URL for your application."
